version: "3.7"

services:
  lucielle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lucielle
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    environment:
      - MONGO_URI="mongodb://root:2020@mdb"
    ports:
      - "8082:3000"
    restart: always
    networks:
      - red

  mdb:
    container_name: mdb
    image: mongo
    ports:
      - "8081:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=2020"
      - "MONGO_INITDB_DATABASE=presupuesto"
    restart: always
    networks:
      - red

networks:
  red: