version: "3.7"

services:
  lucielle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lucielle
    #volumes:
    #  - ./data/app :/usr/src/app
    #  - ./data :/home/node/app/nodemon.json
    environment:
      - MONGO_URI="mongodb://root:2020@mdb"
      #mongodb+srv://creep:2020@cluster0.ourzk.azure.mongodb.net/presupuesto?retryWrites=true&w=majority
    ports:
      - "8082:3000"
    restart: always
    networks:
      - red

  mdb:
    container_name: mdb
    image: mongo
    ports:
      - "8081:27017"
    #volumes:
    #  - ./data/mongodb :/data/db
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=2020"
      - "MONGO_INITDB_DATABASE=presupuesto"
    restart: always
    networks:
      - red

networks:
  red:

# docker-compose -f "docker-compose.yml" up -d --build --no-cache