version: '3'
 
services:
  jenkins:
    image: jenkins
    volumes:
      - home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "8080:8080"
    networks:
      - red
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - red
    #environment:
    #  - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
    #  - sonarqube_extensions:/opt/sonarqube/extensions
    #  - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      
  #db:
  #  image: postgres
  #  networks:
  #    - sonarnet
  #  environment:
  #   - POSTGRES_USER=sonar
  #   - POSTGRES_PASSWORD=sonar
  # volumes:
  #   - postgresql:/var/lib/postgresql
  #   - postgresql_data:/var/lib/postgresql/data
      
networks:
  red:
#    driver: bridge

volumes:
  home:
  sonarqube_conf:
  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_bundled-plugins:
#  postgresql:
#  postgresql_data: