version: '3'

services:
  reverse_1:
    container_name: reverse_1
    hostname: reverse_1
    image: nginx
    ports:
      - 8085:80
      - 8086:443
    #volumes:
     # - ./proxy/config:/etc/nginx
     # - ./proxy/certs:/etc/ssl/private
    #networks:
    #  - nginx_default

#networks:
#  nginx_default:

#copiar archivo al contenedor
#docker cp .\proxy-inverso\proxy\config\lucille.conf reverse:/etc/nginx/conf.d/sites-available/

#copiar este archivo
#ln -s ../sites-available/plex.conf .

#copiar del contendor a una carpeta externa
#docker cp reverse:/etc/nginx/nginx.conf .\proxy-inverso\proxy\config\nginx.conf

#copiar del contendor de regreso
#docker cp .\proxy-inverso\proxy\config\nginx.conf reverse:/etc/nginx/

#comprobar sintaxis nginx
#docker exec reverse nginx -t

#reinicar nginx
#docker exec reverse nginx -s reload
